[versions]
apacheCommonsLang = "3.20.0"
apacheCommonsText = "1.15.0"
equalsVerifier = "3.19.4"
gradleJavaConventions = "0.2.0"
hamcrest = "3.0"
jansi = "2.4.2"
jacoco = "0.8.8"
jqwik = "1.9.3"
junit = "6.0.2"
prettier4j = "0.3.2"
toStringVerifier = "1.4.8"

[libraries]
apacheCommonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommonsLang" }
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsText" }
equalsVerifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsVerifier" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
prettier4j = { module = "com.opencastsoftware:prettier4j", version.ref = "prettier4j" }
toStringVerifier = { module = "com.jparams:to-string-verifier", version.ref = "toStringVerifier" }

[plugins]
gradleJavaConventions = { id = "com.opencastsoftware.gradle.java-conventions", version.ref = "gradleJavaConventions" }
